spring:
  #数据源配置
  datasource:
    #mysql驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    #连接本地数据库EveryShare
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/e_commerce?serverTimezone=UTC
  servlet:
    #多文件上传配置
    multipart:
      #开启文件上传支持
      enabled: true
      #将文件写入磁盘的阈值
      file-size-threshold: 0B
      #上传文件的保存位置
      location: D:/EveryShareImg/
      #上传的单个文件的最大大小
      max-file-size: 1MB
      #请求（多个文件）最大大小
      max-request-size: 10MB
      #关闭文件延迟解析
      resolve-lazily: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名，也可实体类字段上加上@TableLogic注解
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值


